[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
authors = ["Tony Mattheys"]
about = "A small (set of) program(s) which I am using to try out some Rust concepts."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
